{{- $glooMeshMgmtServer := $.Values.glooMeshMgmtServer}}

# Service for gloo-mesh-mgmt-server which exposes stats port and communicates with the Gloo Mesh UI
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo-mesh-mgmt-server
  annotations:
    app.kubernetes.io/name: gloo-mesh-mgmt-server
  name: gloo-mesh-mgmt-server-ui
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: gloo-mesh-mgmt-server
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ $glooMeshMgmtServer.ports.grpcUI }}
    - name: stats
      port: {{ $glooMeshMgmtServer.ports.stats }}