apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: argo-workspace-settings
  namespace: argocd
spec:
  importFrom:
  - workspaces:
    - name: gateways
    resources:
    - kind: SERVICE
  exportTo:
  - workspaces:
    - name: gateways
    resources:
    - kind: SERVICE
      labels:
        app.kubernetes.io/name: argocd-server
    - kind: ALL
      labels:
        expose: "true"
  options:
    federation:
      enabled: true
      hostSuffix: global
      #serviceSelector:
      #- workspace: bookinfo
      #  labels:
      #    app: reviews