kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rate-limiter
  namespace: {{ .Release.Namespace }}
  labels:
    app: rate-limiter
  {{- include "rate-limiter.extraLabels" . | nindent 4 }}
rules:
- apiGroups:
  - ratelimit.solo.io
  resources:
  - ratelimitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.solo.io
  resources:
  - ratelimitconfigs/status
  verbs:
  - get
  - update

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rate-limiter
  namespace: {{ .Release.Namespace }}
  labels:
    app: rate-limiter
  {{- include "rate-limiter.extraLabels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: rate-limiter
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: rate-limiter
  apiGroup: rbac.authorization.k8s.io