kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: gloo-mesh-agent-cluster1
  namespace: gloo-mesh
spec:
  commonName: gloo-mesh-agent-cluster1
  dnsNames:
    # Must match the cluster name used in the helm chart install
    - "cluster1"
  # 1 year life
  duration: 8760h0m0s
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: relay-root-ca
  renewBefore: 8736h0m0s
  secretName: gloo-mesh-agent-cluster1-tls-cert
  usages:
    - digital signature
    - key encipherment
    - client auth
    - server auth
  privateKey:
    algorithm: "RSA"
    size: 4096