apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-cluster1-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-mesh-aoa/
    targetRevision: 1.12-v2-rc1-certmanager-single-extauth
    path: environments/cluster1/apps/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false