apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-cluster1-infra
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-mesh-aoa/
    targetRevision: gehc-poc
    path: environments/cluster1/infra/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true