apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: admin-workspace
  namespace: gloo-mesh
  labels:
    allow_ingress: "true"
spec:
  workloadClusters:
  - name: mgmt
    namespaces:
    - name: argocd
    - name: gloo-mesh
  - name: cluster1
    namespaces:
    - name: argocd
  - name: cluster2
    namespaces:
    - name: argocd