apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: bookinfo
  namespace: gloo-mesh
  labels:
    allow_ingress: "true"
spec:
  workloadClusters:
  - name: cluster1
    namespaces:
    - name: bookinfo-frontends-foo
    - name: bookinfo-backends-foo
  - name: cluster2
    namespaces:
    - name: bookinfo-frontends-bar
    - name: bookinfo-backends-bar