apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-mgmt-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/distributethe6ix/gloo-mesh-aoa/
    targetRevision: 1.13-v2.0.7-certmanager-selfmanaged
    path: environments/mgmt/apps/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false