apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-mgmt-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-mesh-aoa/
    targetRevision: aoaoa
    path: environments/mgmt/apps/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false