apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-cluster2-mesh-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-mesh-aoa/
    targetRevision: 1.12-v2.0.5
    path: environments/cluster2/mesh-config/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false