apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hipstershop-frontend-vs
spec:
  gateways:
  - hipstershop-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        exact: "/hipstershop"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: frontend
        port:
          number: 80