apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  name: add-abort-500-policy
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: cluster2
          name: ratings
          namespace: default
  policy:
    faultInjection:
      abort:
        httpStatus: 500
      percentage: 100