rateLimiter:
  logLevel: INFO
  # Watch all namespaces by default
  watchNamespace: ""
  image:
    pullPolicy: IfNotPresent
    registry: gcr.io/gloo-mesh
    repository: rate-limiter
    tag: 0.5.6
  resources:
    requests:
      cpu: 125m
      memory: 256Mi
  ports:
    grpc: 8083
    ready: 8084
    debug: 9091
  readyPath: /ready
redis:
  image:
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: redis
    tag: 6.2.6
  service:
    port: 6379
    name: redis
  enabled: true
