apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-cluster3-cluster-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-mesh-aoa/
    targetRevision: 2-cluster-demo
    path: environments/cluster3/cluster-config/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false