apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-cluster3-mesh-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/gloo-mesh-aoa/
    targetRevision: 3-clusters-mixed
    path: environments/cluster3/mesh-config/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false