apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: RouteTable
metadata:
  name: bookinfo-routetable
  namespace: gloo-mesh
spec:
  routes:
  - matchers:
    - uri:
        exact: /productpage
    - uri:
        prefix: /static
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    name: productpage
    routeAction:
      destinations:
      - kubeService:
          clusterName: cluster1
          name: productpage
          namespace: default
        weight: 30
      - kubeService:
          clusterName: cluster2
          name: productpage
          namespace: default
        weight: 30
      - kubeService:
          clusterName: cluster3
          name: productpage
          namespace: default
        weight: 40
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualGateway
metadata:
  name: bookinfo-virtualgateway
  namespace: gloo-mesh
spec:
  connectionHandlers:
  - http:
      routeConfig:
      - virtualHostSelector:
          namespaces:
          - gloo-mesh
  ingressGatewaySelectors:
  - destinationSelectors:
    - kubeServiceMatcher:
        labels:
          istio: ingressgateway
        namespaces:
        - istio-system
    portName: http2
---
apiVersion: networking.enterprise.mesh.gloo.solo.io/v1beta1
kind: VirtualHost
metadata:
  name: bookinfo-virtualhost
  namespace: gloo-mesh
spec:
  domains:
  - '*'
  routes:
  - delegateAction:
      selector:
        namespaces:
        - gloo-mesh
    matchers:
    - uri:
        prefix: /
---
apiVersion: networking.mesh.gloo.solo.io/v1
kind: TrafficPolicy
metadata:
  name: reviews-trafficshift
  namespace: gloo-mesh
spec:
  destinationSelector:
  - kubeServiceMatcher:
      clusters:
      - cluster1
      - cluster2
      - cluster3
      labels:
        app: reviews
  routeSelector:
    - virtualHostSelector:
        namespaces:
          - gloo-mesh
        labels:
          type: north-south
  policy:
    trafficShift:
      destinations:
        - kubeService:
            clusterName: cluster1
            name: reviews
            namespace: default
          weight: 0
        - kubeService:
            clusterName: cluster2
            name: reviews
            namespace: default
          weight: 0
        - kubeService:
            clusterName: cluster3
            name: reviews
            namespace: default
          weight: 100
