apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: gm-ui-rt-443
  namespace: gloo-mesh
spec:
  hosts:
  - '*'
  http:
  - forwardTo:
      destinations:
      - kind: VIRTUAL_DESTINATION
        port:
          number: 8090
        ref:
          cluster: mgmt
          name: gm-ui-vd
          namespace: gloo-mesh
    labels:
      waf: "true"
    name: gloo-mesh-ui
    matchers:
    - uri:
        prefix: /
    - uri:
        prefix: /graph
    - uri:
        prefix: /gateways
    - uri:
        prefix: /policies
  virtualGateways:
  - cluster: mgmt
    name: north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []
---
apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  labels:
    expose: "true"
  name: gm-ui-vd
  namespace: gloo-mesh
spec:
  hosts:
  - gm-ui.mgmt.global
  ports:
  - number: 8090
    protocol: HTTP
  services:
  - cluster: mgmt
    labels:
      app: gloo-mesh-ui
    namespace: gloo-mesh
