apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: global
  namespace: gloo-mesh
spec:
  options:
    eastWestGateways:
    - selector:
        labels:
          istio: eastwestgateway
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: admin-workspace-settings
  namespace: gloo-mesh
spec:
  exportTo:
  - resources:
    - kind: SERVICE
      labels:
        app.kubernetes.io/name: argocd-server
    - kind: ALL
      labels:
        expose: "true"
    workspaces:
    - name: gateways
  importFrom:
  - resources:
    - kind: SERVICE
    workspaces:
    - name: gateways
  options:
    federation:
      enabled: true
      hostSuffix: global
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: gateways
  namespace: istio-gateways
spec:
  exportTo:
  - resources:
    - kind: SERVICE
    workspaces:
    - selector:
        allow_ingress: "true"
  importFrom:
  - resources:
    - kind: SERVICE
    - kind: ALL
      labels:
        expose: "true"
    workspaces:
    - selector:
        allow_ingress: "true"